In [6]:
import numpy as npy

# 行ベクトルの定義
a = npy.array([1,2])
# 列ベクトルの定義
b = npy.array([[2],[4],[6]])

print("★行ベクトル")
print(a)
print("★列ベクトル")
print(b)

★行ベクトル
[1 2]
★列ベクトル
[[2]
 [4]
 [6]]


In [8]:
import numpy as npy

# 行ベクトルの定義
a = npy.array([[1,2]])

print("★行ベクトル")
print(a)
print("★転置後の列ベクトル")
print(a.T)
print(a.T.T)

★行ベクトル
[[1 2]]
★転置後の列ベクトル
[[1]
 [2]]
[[1 2]]


In [15]:
import numpy as npy

# 行ベクトルの定義
a = npy.array([1,2])
b = npy.array([3,8])

print(a.dot(b))

19


In [17]:
import numpy as npy

# 行ベクトルの定義
a = npy.array([1,2])
b = npy.array([3,4])

# ベクトルの大きさを求まる
anum = npy.linalg.norm(a)
bnum = npy.linalg.norm(b)

print(a)
print(anum)
print(b)
print(bnum)

[1 2]
2.23606797749979
[3 4]
5.0


In [33]:
import math

# πを取得
pi = math.pi
# πから角度
radian = math.degrees(pi)

cos0 = math.cos(math.radians(0))
cos90 = math.cos(math.radians(90))
cos180 = math.cos(math.radians(180))

print("cos0")
print(cos0)
print("cos90")
print(cos90)
print("cos180")
print(cos180)

cos0
1.0
cos90
6.123233995736766e-17
cos180
-1.0
