In [1]:
import numpy as npy

# 行列の定義
A = npy.array([[2,0,5],[6,1,2]])
B = npy.array([[1,5,3],[10,0,6]])

add = A+B
sub = A-B
print("加算の結果")
print(add)
print("減算の結果")
print(sub)


加算の結果
[[ 3  5  8]
 [16  1  8]]
減算の結果
[[ 1 -5  2]
 [-4  1 -4]]


In [2]:
import numpy as npy

# 行列の定義
A = npy.array([[2,0,5],[6,1,2]])

result1 = 2*A
result2 = -3*A
result3 = 0.1*A

print("２倍")
print(result1)
print("－３倍")
print(result2)
print("０．１倍")
print(result3)

２倍
[[ 4  0 10]
 [12  2  4]]
－３倍
[[ -6   0 -15]
 [-18  -3  -6]]
０．１倍
[[0.2 0.  0.5]
 [0.6 0.1 0.2]]


In [3]:
import numpy as npy

# ベクトルの定義
A = npy.array([[2,0,5]])
B = npy.array([[3],[2],[-1]])

result1 = A.dot(B)
result2 = B.dot(A)

print("A×Bの解")
print(result1)
print("B×Aの解")
print(result2)


A×Bの解
[[1]]
B×Aの解
[[ 6  0 15]
 [ 4  0 10]
 [-2  0 -5]]


In [4]:
import numpy as npy
# 行列の定義
A = npy.array([[2,0,5],[4,-2,1]])
B = npy.array([[3,5],[2,-3],[-1,1]])

result1 = A.dot(B)
result2 = B.dot(A)

print("A×Bの解")
print(result1)
print("B×Aの解")
print(result2)


A×Bの解
[[ 1 15]
 [ 7 27]]
B×Aの解
[[ 26 -10  20]
 [ -8   6   7]
 [  2  -2  -4]]


In [6]:
import numpy as npy
# 正方行列の乗算
# 行列の定義
A = npy.array([[2,0],[4,-2]])
B = npy.array([[3,5],[2,-3]])

result1 = A.dot(B)
result2 = B.dot(A)

print("A×Bの解")
print(result1)
print("B×Aの解")
print(result2)


A×Bの解
[[ 6 10]
 [ 8 26]]
B×Aの解
[[ 26 -10]
 [ -8   6]]


In [7]:
import numpy as npy
# 単位行列の乗算
# 行列の定義
A = npy.array([[2,0],[4,-2]])
B = npy.array([[1,0],[0,1]])

result1 = A.dot(B)
result2 = B.dot(A)

print("A×Bの解")
print(result1)
print("B×Aの解")
print(result2)


A×Bの解
[[ 2  0]
 [ 4 -2]]
B×Aの解
[[ 2  0]
 [ 4 -2]]


In [13]:
import numpy as npy
# 逆行列の算出
# 行列の定義
A = npy.array([[1,2],[3,4]])
B = npy.array([[3,2,-2],[2,5,6],[10,-5,2]])
C = npy.array([[1,2],[2,4]])

result1 = npy.linalg.inv(A)
result2 = npy.linalg.inv(B)
#result3 = npy.linalg.inv(C)

print("Aの逆行列")
print(result1)
print("Bの逆行列")
print(result2)
print("Cの逆行列")
#print(result3)

Aの逆行列
[[-2.   1. ]
 [ 1.5 -0.5]]
Bの逆行列
[[ 0.11363636  0.01704545  0.0625    ]
 [ 0.15909091  0.07386364 -0.0625    ]
 [-0.17045455  0.09943182  0.03125   ]]
Cの逆行列


In [1]:
import numpy as npy
# 転置操作
# 行列の定義
A = npy.array([[2,4,1],[-6,2,11]])

AT = A.T

print("行列A")
print(A)
print("行列Aの転置")
print(AT)


行列A
[[ 2  4  1]
 [-6  2 11]]
行列Aの転置
[[ 2 -6]
 [ 4  2]
 [ 1 11]]


In [2]:
import numpy as npy
# 連立方程式を解く
# 行列の定義
left = npy.array([[2,-1],[3,2]])
right = npy.array([[10],[1]])
# 逆行列を求める
left_rev = npy.linalg.inv(left)
# 逆行列を乗算する
result = left_rev.dot(right)

print("逆行列")
print(left_rev)
print("連立方程式の解")
print(result)

逆行列
[[ 0.28571429  0.14285714]
 [-0.42857143  0.28571429]]
連立方程式の解
[[ 3.]
 [-4.]]


In [3]:
import numpy as npy
# 連立方程式を解く
# 行列の定義
left = npy.array([[3,1,-1],[-2,4,-3],[7,3,2]])
right = npy.array([[10],[7],[1]])
# 逆行列を求める
left_rev = npy.linalg.inv(left)
# 逆行列を乗算する
result = left_rev.dot(right)

print("逆行列")
print(left_rev)
print("連立方程式の解")
print(result)

逆行列
[[ 0.25       -0.07352941  0.01470588]
 [-0.25        0.19117647  0.16176471]
 [-0.5        -0.02941176  0.20588235]]
連立方程式の解
[[ 2.]
 [-1.]
 [-5.]]
