In [14]:
import numpy as npy

list = npy.arange(15)
# 数列の場合
a = npy.array([[1,2],[3,4],[5,6]])

print(list[:5])
print(list[5:])
print(list[5:10])
print(a[:2])

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14]
[5 6 7 8 9]
[[1 2]
 [3 4]]


In [16]:
import numpy as npy

list = npy.array([1,2,3,4,10,11,12])

print(list > 2)

[False False  True  True  True  True  True]


In [18]:
import numpy as npy

list = npy.array([1,2,3,4,10,11,12])

turelist = list[list > 2]

print(turelist)

[ 3  4 10 11 12]


In [32]:
import numpy as npy

alist = npy.array([1,2,3,4,10,11,12])
boollist = npy.array([False,False,True,True,True,True,True])

reultlist = alist[boollist]
falselist = alist[False]
truelist = alist[True]

print(boollist)
print("resultlist= " + str(reultlist))
print(falselist)
print(truelist)


[False False  True  True  True  True  True]
resultlist= [ 3  4 10 11 12]
[]
[[ 1  2  3  4 10 11 12]]


In [52]:
import numpy as npy

alist = npy.array([1,2,3,4,10,11,12])
blist = npy.array([1,2,3,4,10,11,12])
clist = npy.array([1,2,3,4,10,11,12])

alist[alist > 2] = 10
blist[blist > 2] + 10
clist[clist > 2] = clist[clist > 2] + 10

print(alist)
print(blist)
print(clist)

[ 1  2 10 10 10 10 10]
[ 1  2  3  4 10 11 12]
[ 1  2 13 14 20 21 22]


In [55]:
message = "デフォルト"
def func():
    global message
    message = message + "関数の処理"
    print(message)

print(message)
func()


デフォルト
デフォルト関数の処理


In [64]:
import numpy as npy
message = "デフォルト"

def func(num):
    global message
    message = message + "関数の処理"
    numlist = npy.arange(num)
    print("message = " + message)
    print("関数内のリスト = " + str(numlist))
    return numlist
    

print(message)
resultlist = func(10)
print(resultlist[:5])

デフォルト
message = デフォルト関数の処理
関数内のリスト = [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [68]:
import numpy as npy
message = "デフォルト"

def func(num):
    global message
    message = message + "関数の処理"
    numlist = npy.arange(num)
    print("message = " + message)
    print("関数内のリスト = " + str(numlist))
    return message, numlist
    

resultlist = func(10)
print(resultlist)

resultmessage, resultlist2 = func(5)
print(resultmessage)
print(resultlist2)


message = デフォルト関数の処理
関数内のリスト = [0 1 2 3 4 5 6 7 8 9]
('デフォルト関数の処理', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))
message = デフォルト関数の処理関数の処理
関数内のリスト = [0 1 2 3 4]
デフォルト関数の処理関数の処理
[0 1 2 3 4]


In [80]:
import numpy as npy

message = "ファイル保存用メッセージ"
# メッセージをファイルに保存する
npy.save('testfile.npy', message)
# ファイルの内容を読み取る
result = npy.load('testfile.npy')

print(result)

ファイル保存用メッセージ


In [74]:
import time
time.time()

1573571224.9515214