In [4]:
import numpy as npy

#ベクトルの定義
a = npy.array([1,10])
b = npy.array([2,4])

addvec = a + b
subvec = a - b

print("ベクトルの和は" + str(addvec))
print("ベクトルの差は" + str(subvec))

ベクトルの和は[ 3 14]
ベクトルの差は[-1  6]


In [7]:
import numpy as npy

#ベクトルの定義
a = npy.array([1,10])
b = npy.array([2,4])

multivec = a * b
divvec = a / b

print("ベクトルの積は" + str(multivec))
print("ベクトルの商は" + str(divvec))

ベクトルの積は[ 2 40]
ベクトルの商は[0.5 2.5]


In [8]:
import numpy as npy

#ベクトルの定義
a = npy.array([1,10])

vec = 2*a

print("ベクトルのスカラー倍" + str(vec))

ベクトルのスカラー倍[ 2 20]


In [10]:
import numpy as npy

#ベクトルの定義
a = npy.array([1,10])
b = npy.array([2,4])

addvec = a + b

#一番目の成分を取り出す
num = addvec[0]
#成分を書き換える
addvec[0] = 100

print("取り出した成分＝" + str(num))
print("書き換え後の成分＝" + str(addvec[0]))

取り出した成分＝3
書き換え後の成分＝100


In [13]:
import numpy as npy

# 0から生成
a = npy.arange(5)
# 2から4まで生成
b = npy.arange(2,5)

print("a=" + str(a))
print("b=" + str(b))

a=[0 1 2 3 4]
b=[2 3 4]


In [16]:
import numpy as npy

#ベクトルの定義
a = npy.array([1,10])
b = npy.array([2,4])

# 参照先をコピーする
a2 = a
# 値をコピーする
ac = a.copy()

print("コピー直後 a=" + str(a))
print("コピー直後 a2=" + str(a2))
print("コピー直後 ac=" + str(ac))

# 処理
a2[0] = 2
ac[0] = 3

print("処理後 a=" + str(a))
print("処理後 a2=" + str(a2))
print("処理後 ac=" + str(ac))

コピー直後 a=[ 1 10]
コピー直後 a2=[ 1 10]
コピー直後 ac=[ 1 10]
処理後 a=[ 2 10]
処理後 a2=[ 2 10]
処理後 ac=[ 3 10]


In [18]:
import numpy as npy

# 行列の定義
a = npy.array([[1,10],[2,5]])

print("行列a=" + str(a))

行列a=[[ 1 10]
 [ 2  5]]


In [27]:
import numpy as npy

# 行列の定義
a = npy.array([[1,10],[2,5],[1,1]])
h, w = a.shape

print("行列サイズ=" + str(a.shape))
print("行列の高さ=" + str(h) + "、行列の幅=" + str(w))
print("行列サイズのタイプ=" + str(type(a.shape)))

行列サイズ=(3, 2)
行列の高さ=3、行列の幅=2
行列サイズのタイプ=<class 'tuple'>


In [28]:
import numpy as npy

# 行列の定義
a = npy.array([[1,10],[2,5],[1,1]])

# 行列の取得参照
b = a[0]
c = a[1,1]
# 行列の書き換え
a[2,0] = 100

print(a)
print(b)
print(c)

[[  1  10]
 [  2   5]
 [100   1]]
[ 1 10]
5


In [32]:
import numpy as npy

# 行列の定義
zeros = npy.zeros((2,3))
ones = npy.ones(7)

print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1.]


In [50]:
import numpy as npy

# ランダム行列の定義
rands = npy.random.rand(3,3)

print(rands)
# ランダムな整数値の行列
print(npy.random.randint(1,10,(2,3)))
print(npy.random.randint(1,10,(2,3)))

[[0.69891983 0.57141852 0.62646802]
 [0.69179131 0.46572066 0.87677665]
 [0.10003993 0.51280035 0.76016474]]
[[8 2 9]
 [2 5 5]]
[[7 5 9]
 [1 8 3]]


In [2]:
import numpy as npy

# 行列の定義
a = npy.array([[1,2],[3,4],[5,6]])
b = npy.array([[2,2],[2,2],[2,2]])

# 行列の算術
add = a + b
sub = a - b

# 結果出力
print("数列の和は" + str(add))
print("数列の差は" + str(sub))


数列の和は[[3 4]
 [5 6]
 [7 8]]
数列の差は[[-1  0]
 [ 1  2]
 [ 3  4]]


In [17]:
import numpy as npy

# 行列の定義
a = npy.array([[1,2],[3,4]])
b = npy.array([[1,2],[3,4]])
c = npy.array([2,5])

# 行列の算術
result1 = a.dot(b)
result2 = a.dot(c)

# 結果出力
print("2×2同士の積= " + str(result1))
print("2×2と2×1の積= " + str(result2))


2×2同士の積= [[ 7 10]
 [15 22]]
2×2と2×1の積= [12 26]


##### import numpy as npy

# 行列の定義
a = npy.array([[1,2],[5,9]])
b = npy.array([[1,2],[3,4]])
c = npy.array([2,5])

# 行列の算術
result1 = npy.sqrt(a)
result2 = npy.exp(a)
result3 = npy.log(result2)
result4 = npy.mean(a)
result

# 結果出力
print("平方根= " + str(result1))
print("指数関数= " + str(result2))
print("result2の対数関数= " + str(result3))
print("平均= " + str(result4))


In [24]:
import numpy as npy

# 行列の定義
a = npy.array([[1,2],[5,9]])
b = npy.array([[1,2],[3,4]])
c = npy.array([2,5])

# 行列の算術
result1 = npy.sqrt(a)
result2 = npy.exp(a)
result3 = npy.log(result2)
result4 = npy.mean(a)
result5 = npy.std(a)

# 結果出力
print("平方根= " + str(result1))
print("指数関数= " + str(result2))
print("result2の対数関数= " + str(result3))
print("平均= " + str(result4))
print("標準偏差= " + str(result5))

平方根= [[1.         1.41421356]
 [2.23606798 3.        ]]
指数関数= [[2.71828183e+00 7.38905610e+00]
 [1.48413159e+02 8.10308393e+03]]
result2の対数関数= [[1. 2.]
 [5. 9.]]
平均= 4.25
標準偏差= 3.112474899497183
